---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Интернет-магазин должен иметь удобный интерфейс
  - На сайте должна быть Политика конфиденциальности и файлов cookie
  - Макет магазина должен быть адаптирован к мобильным устройствам.
  - Магазин должен быть одностраничным приложением (SPA) и не перезагружать страницу во время использования.
  - Каталог товаров должен быть удобным для поиска и фильтрации.
  - Каталог товаров должен отображать название, рейтинг, цену и скидку каждого товара.
  - Пользователь должен иметь возможность добавлять несколько товаров в корзину.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Магазин должен иметь страницу оплаты.
  - Корзина должна храниться в сессии браузера для легкого доступа и сохранения.
